### ISSUE TITLE
Further simplification of sqlitex.Pool.Get is not correct

### ISSUE THREAD

**Issue by anacrolix** [crawshaw/sqlite#105]
I believe the simplification in https://github.com/crawshaw/sqlite/commit/c394106d93fa5bf54e213be1bbab1cb846380bf7 after https://github.com/crawshaw/sqlite/pull/104#issuecomment-727685441 is not correct. It's still necessary to check that the pool is not closed after obtaining the mutex.

**Comment by AdamSLevy** [comment]
I see. Yes you're right.

**Comment by anacrolix** [comment]
FWIW it's actually broken since this change, and it may be worthwhile reverting it until it's refactored correctly.

**Comment by anacrolix** [comment]
@AdamSLevy I created a PR to revert the change.

**Comment by anacrolix** [comment]
Thanks!
