### ISSUE TITLE
How to insert timestamp value

### ISSUE THREAD

**Issue by lunemec** [crawshaw/sqlite#14]
Hi,
I tried using your library to insert/group large ammounts of data with sqlite, but I'm having problem inserting TIMESTAMP values:

Create table (called only once).
```go
	sql := `CREATE TABLE dns(
		time DATETIME NOT NULL
	)`
	stmt, _, err := conn.PrepareTransient(sql)
	if err != nil {
		return errors.Wrap(err, "unable to create new table")
	}
	_, err = stmt.Step()
	if err != nil {
		return errors.Wrap(err, "unable to create new table")
	}
	err = stmt.Finalize()
	if err != nil {
		return errors.Wrap(err, "unable to finalize create table")
	}
```

Inserts:
```go
	stmt := conn.Prep("INSERT INTO dns VALUES($time)")
	for input := range data {
		stmt.SetText("$time", parseTimestamp(input.Timestamp).UTC().Format(time.RFC3339))
		stmt.SetText("$server", input.Server)
		stmt.SetInt64("$delay_us", int64(input.DelayUS))
	}
```

From what I read in SQLite docs, the RFC3339 format should be ok without any changes. I also tried this format: `"2006-01-02 15:04:05.99"` without success.

This is error I get: `sqlite.BindText: SQLITE_MISUSE (INSERT INTO dns VALUES($time))`.

**Comment by crawshaw** [comment]
SQLite does not have special handling for dates and times, they are either strings formatted as you choose, or integers. It is up to your software to interpret them. There are built-in functions that expect particular formats, if you use them you will need to match those formats: https://www.sqlite.org/lang_datefunc.html You don't have to use them.

The error you have here is I believe unrelated. You are trying to insert $server and $delay_us values, but they are not defined in your statement.
