### ISSUE TITLE
Stmt.Reset needed to release locks

### ISSUE THREAD

**Issue by daaku** [crawshaw/sqlite#17]
Prepared statements seem to hold locks in a surprising way (to me at least).

This might just be a documentation issue, as adding a `defer stmt.Reset()` (or `Finalize`) will cause the lock to be released as expected. The top level package doc example code may want to include this line if this is the case.

Possibly there is a technical solution where putting the `Conn` back in the pool ensures statements pulled out since the last `Get` are `Reset` automatically.

Here's a trimmed down example where I initially ran into this:

```go
package main

import (
	"fmt"

	"crawshaw.io/sqlite"
	"crawshaw.io/sqlite/sqliteutil"
)

func printUserVersion(dbPool *sqlite.Pool) {
	db := dbPool.Get(nil)
	defer dbPool.Put(db)

	stmt := db.Prep("PRAGMA user_version;")
	defer stmt.Reset() // removing this will cause a lock related stall
	if _, err := stmt.Step(); err != nil {
		panic(err)
	}
	currentVersion := stmt.ColumnInt(0)
	fmt.Println("version", currentVersion)
}

func create(dbPool *sqlite.Pool) {
	db := dbPool.Get(nil)
	defer dbPool.Put(db)

	err := sqliteutil.ExecScript(db, `
create table names (name text);
pragma user_version = 1;
`)
	if err != nil {
		panic(err)
	}
}

func drop(dbPool *sqlite.Pool) {
	db := dbPool.Get(nil)
	defer dbPool.Put(db)

	err := sqliteutil.ExecScript(db, `
drop table names;
pragma user_version = 2;
`)
	if err != nil {
		panic(err)
	}
}

func main() {
	dbPool, err := sqlite.Open("file:mem0:?mode=memory", 0, 10)
	if err != nil {
		panic(err)
	}
	defer dbPool.Close()

	printUserVersion(dbPool)
	create(dbPool)
	printUserVersion(dbPool)
	drop(dbPool)
	printUserVersion(dbPool)
}
```

**Comment by crawshaw** [comment]
Some more details (which I really need to turn into docs):

When `stmt.Step()` return true, you are running a statement. That means you are probably holding at least a read lock. This is true until you either call `stmt.Step()` and get a false, or you call `stmt.Reset()`.

As an aside, for your particular example I'd recommend `sqliteutil.ResultInt(db.Prep("PRAGMA user_version;"))` which does the cleanup.
