### ISSUE TITLE
Run tests on Travis CI

### ISSUE THREAD

**Issue by fasterthanlime** [crawshaw/sqlite#22]
I'm doing this, one problem is that https://crawshaw.io/iox/ioxtest?go-get=1 is a 404:

```
4.36s$ go get -t -v ./...
Fetching https://crawshaw.io/iox/ioxtest?go-get=1
Parsing meta tags from https://crawshaw.io/iox/ioxtest?go-get=1 (status code 404)
package crawshaw.io/iox/ioxtest: unrecognized import path "crawshaw.io/iox/ioxtest" (parse https://crawshaw.io/iox/ioxtest?go-get=1: no go-import meta tags ())
```

@crawshaw I've seen you tweet about renaming a package others are using - is this the one? If you're planning on renaming it, it would be easier to do before setting up Travis.

**Comment by crawshaw** [comment]
Should be fixed now. `mkdir /tmp/foo && cd /tmp/foo && GOPATH=$(pwd) go get crawshaw.io/iox/ioxtest` now works.
