### ISSUE TITLE
Wrapped errors (github.com/pkg/errors)

### ISSUE THREAD

**Issue by fasterthanlime** [crawshaw/sqlite#28]
My fork unwraps errors passed to `ErrCode`:

https://github.com/fasterthanlime/sqlite/blob/2c204735769c318990e7b4e133a4f770fea28498/error.go#L341-L352

I'm using https://github.com/pkg/errors throughout my codebases for proper stack traces, etc.

---

It's not the only Go package that allows that, though, so maybe unwrapping should be pluggable?

Something like:

```go
sqlite.SetErrorUnwrapper(errors.Cause)
```

The signature would be:

```go
type ErrorUnwrapper func (err error) error
var errorUnwrapper ErrorUnwrapper

func SetErrorUnwrapper(eu ErrorUnwrapper) { /* ... */ }
```

In `ErrCode`, there'd be a `errorUnwrapper != nil` check - this should be pretty cheap for folks who don't wrap errors.

What do you think? I know it's not ideal, but I can't think of a better solution right now.

If this approach is chosen, the docs should be *very clear* that only applications should call this, not libraries, and maybe calling `SetErrorUnwrapper` a second time should panic.

**Comment by fasterthanlime** [comment]
Alternative idea:

```go
type causer interface {
  Cause() error
}

func ErrCode(err error) ErrorCode { 
  if ce, ok := err.(causer); ok {
    return ErrCode(ce.Cause())
  }

  // ... current ErrCode code
}
```

This would support `github.com/pkg/errors` would referencing it.

Just two data points:

  * https://github.com/pkg/errors is currently imported by 12131 packages
  * https://github.com/go-errors/errors is currently imported by 387 packages

**Comment by fasterthanlime** [comment]
> Your second alternative is not so bad, but I wonder if this belongs in the sqlite package. I think a user can write their own ErrCode wrapper function and use that instead of sqlite.ErrCode, which can do any kind of handling they want. Is that not the case?

Well, `ErrCode()` is used in sqliteutil to determine whether to `RELEASE` or `ROLLBACK` at the end of a savepoint so.. yes and no.

I suppose I could reimplement `Save` myself, but as we've seen today, it is tricky to get right :)

**Comment by crawshaw** [comment]
`sqliteutil.Save` is a good argument. If you want to send a PR that looks for a causer interface I'll take it.

**Comment by crawshaw** [comment]
Oh you did already. :-)
