### ISSUE TITLE
HAVE_USLEEP needs to be enabled on unix

### ISSUE THREAD

**Issue by bvinc** [crawshaw/sqlite#33]
Hello, I'm on the guy on github that was also writing a go sqlite package.

https://github.com/bvinc/go-sqlite-lite/blob/master/sqlite3/sqlite3.go#L29-L30

I noticed that you didn't have this line in your cgo CFLAGS.  SQLite, when built normally on a unix system, uses a `configure` script to make sure that the function `usleep` is available which allows sqlite to sleep for a non-integer number of seconds.  The function `usleep` is pretty much always available on any modern unix system.  But since you're not using their configure script, you have to enable this manually with cgo.

If you don't enable this, you get a particularly nasty footgun that's hard to detect.  When two sqlite transactions conflict, one might get SQLITE_BUSY, so you want to set a busy timeout of let's say 5 seconds.  By default, when a transaction is busy and is retrying during the busy timeout, it sleeps a random small number of milliseconds before trying again.  But if HAVE_USLEEP is not defined, it can only sleep whole seconds, and it'll only have 5 chances to try again.

This blog post explains the problem pretty well.

http://beets.io/blog/sqlite-nightmare.html

**Comment by crawshaw** [comment]
OK I think this is fixed. It's unfortunately not easy to write a test for. Thanks for the report!
