### ISSUE TITLE
sqlite: online backup API

### ISSUE THREAD

**Issue by crawshaw** [crawshaw/sqlite#36]
https://www.sqlite.org/backup.html

Useful in environments without an easily-snapshotted SAN (which have been looking more interesting to me lately).

**Comment by gedw99** [comment]
this is a really useful extension for me at least.

i guess the online backup server would need to be written on golang.

**Comment by crawshaw** [comment]
I don't have any clear need for this API any more, as `VACUUM INTO` does everything I want: https://www.sqlite.org/lang_vacuum.html#vacuuminto

**Comment by AdamSLevy** [comment]
The backup API has been added.
