### ISSUE TITLE
Add a v0.1.0 tag

### ISSUE THREAD

**Issue by zombiezen** [crawshaw/sqlite#38]
Please consider adding a `v0.1.0` tag to the repository for tracking via the upcoming Go module support.

**Comment by crawshaw** [comment]
Sure. Questions, as I've been avoiding modules so far:

- Does v0 let me make breaking API changes without bumping the major number?
- Does the repo version apply to all packages in the repository?

Thanks.

**Comment by zombiezen** [comment]
As per [Semantic Versioning rules](https://semver.org/#spec-item-4), anything can change at any point under major version 0. Convention is generally to bump the minor number when things change and to bump the patch number when you are purely fixing bugs.

You can split up your repository into multiple modules (see the "Multiple-Module Repositories" section of [Russ's Defining Go Modules post](https://research.swtch.com/vgo-module)) by placing a go.mod file at the root of the module you want to version and then creating a specially formatted tag on the repository. The boundaries can evolve over time: I recommend keeping the whole repository as one module while you're in v0 stage, just for simplicity sake.

**Comment by crawshaw** [comment]
Thanks! This repository should have a v0.1.0 tag now.
