### ISSUE TITLE
geopoly support

### ISSUE THREAD

**Issue by crawshaw** [crawshaw/sqlite#42]
Fun new extension: https://www.sqlite.org/geopoly.html

Should it be compiled in by default?

**Comment by gertcuykens** [comment]
Yes please, sqlite is used alot to store geometrie stuff https://en.wikipedia.org/wiki/GeoPackage

**Comment by AdamSLevy** [comment]
Should this really be a default?

**Comment by ksshannon** [comment]
@AdamSLevy I think it should.  It's pretty lightweight, and it can be used with the rtree extension.

**Comment by AdamSLevy** [comment]
merged.
