### ISSUE TITLE
ErrCode isn't always an extended error code

### ISSUE THREAD

**Issue by FiloSottile** [crawshaw/sqlite#5]
A call to ErrCode returned `SQLITE_CONSTRAINT`, when (I think) I would have expected `SQLITE_CONSTRAINT_UNIQUE`.

This might be due to this TODO https://github.com/crawshaw/sqlite/blob/2024f6c692a33c1f5cdcdc2f5bf4ad15810b2595/sqlite.go#L361-L365

**Comment by crawshaw** [comment]
So far I've seen `sqlite3_step` always return extended error codes because the statements are prepared with `sqlite_prepare_v3`.

Do you have some way I can reproduce it?

**Comment by FiloSottile** [comment]
> For historic compatibility, the C-language interfaces return primary result codes by default. The extended result code for the most recent error can be retrieved using the sqlite3_extended_errcode() interface. The sqlite3_extended_result_codes() interface can be used to put a database connection into a mode where it returns the extended result codes instead of the primary result codes.

https://www.sqlite.org/rescode.html

**Comment by FiloSottile** [comment]
(My reproduction case here is just inserting two identical lines in a table with a UNIQUE index.)

**Comment by crawshaw** [comment]
Ah, this is confusing:

> In the legacy interface, the return value will be either SQLITE_BUSY, SQLITE_DONE, SQLITE_ROW, SQLITE_ERROR, or SQLITE_MISUSE. With the "v2" interface, any of the other result codes or extended result codes might be returned as well.

https://www.sqlite.org/c3ref/step.html

I've been seeing extended result codes, so I assumed we were always getting extended result codes. But it appears that sqlite3_prepare_v3 may return extended codes but isn't required to. That's odd.

So yeah, let's set `sqlite3_extended_result_codes`. I'll patch that in now...
