### ISSUE TITLE
sqlitex pkg issues with Go modules

### ISSUE THREAD

**Issue by pentateu** [crawshaw/sqlite#58]
Hi,

I have added Go modules to my project and now Go build is unable to find the sqlitex package.

unknown import path "crawshaw.io/sqlite/sqlitex": cannot find module providing package crawshaw.io/sqlite/sqlitex

I use other packages that are nested (.../sqlite/sqlitex) just like that,but  all from github.com and they work fine.
The same issue happens on CI server and local machine.

Is that related to how the code is hosted?

Anyone else had this issue?

**Comment by crawshaw** [comment]
I think the problem is the lack of go.mod file. I added one, hopefully this fixes it.
