### ISSUE TITLE
cgo warning: built-in function ‘free’ declared as non-function

### ISSUE THREAD

**Issue by AdamSLevy** [crawshaw/sqlite#60]
I get this warning anytime I build this package.

```
cgo-generated-wrappers:7:13: warning: built-in function ‘free’ declared as non-function [-Wbuiltin-declaration-mismatch]
```

Is this warning anything that matters? If not can it be suppressed in some way?

**Comment by AdamSLevy** [comment]
It appears this warning may be safely ignored, but I would still like to better understand its root cause.

**Comment by josharian** [comment]
One possible workaround is to define a C function that calls `free`, and then pass that C function instead of free to the sqlite calls as needed.
