### ISSUE TITLE
go get v0.1.2/v0.1.3 confusion

### ISSUE THREAD

**Issue by distributed** [crawshaw/sqlite#79]
When I import `crawshaw.io/sqlite/sqlitex`, I get an error, `cannot load crawshaw.io/sqlite/sqlitex: module crawshaw.io/sqlite@latest (v0.1.2) found, but does not contain package crawshaw.io/sqlite/sqlitex`.

This is, as the error message states, on v0.1.2. When through `go get` I update to `master`, I get a version `v0.1.3-0.20190520153332-66f853b01dfb` that seems to be after tag `v0.1.3`.

I can not, however, `go get -u` v0.1.3.

You can see how I arrive at these conclusions from my shell session and `main.go` below.

A similar confusion happens on pkg.go.dev. When I visit https://pkg.go.dev/crawshaw.io/sqlite/sqlitex?tab=overview, I see `sqlitex` is on `v0.1.3 (Latest)`. When I click on the module link and thus go to https://pkg.go.dev/mod/crawshaw.io/sqlite the version is now displayed as `v0.1.2`.

I am puzzled as to why this happens. Is this a matter of tags missing in a repo? Github, at least, does not have v0.1.3.

```
distributed@machine:~/tmp/bla$ go mod init bla
go: creating new go.mod: module bla
distributed@machine:~/tmp/bla$ ls
go.mod  main.go # main.go imports crawshaw.io/sqlite/sqlitex
distributed@machine:~/tmp/bla$ go get -u
build bla: cannot load crawshaw.io/sqlite/sqlitex: module crawshaw.io/sqlite@latest (v0.1.2) found, but does not contain package crawshaw.io/sqlite/sqlitex
distributed@machine:~/tmp/bla$ go get -u -v crawshaw.io/sqlite@master
go: finding crawshaw.io master
go: finding crawshaw.io/sqlite master
# crawshaw.io/sqlite
cgo-generated-wrappers:7:13: warning: built-in function ‘free’ declared as non-function [-Wbuiltin-declaration-mismatch]
distributed@machine:~/tmp/bla$ cat go.mod 
module bla

go 1.13

require crawshaw.io/sqlite v0.1.3-0.20190520153332-66f853b01dfb // indirect
distributed@machine:~/tmp/bla$ go get -u -v crawshaw.io/sqlite@v0.1.3
go: finding crawshaw.io/sqlite v0.1.3
get "crawshaw.io/sqlite": found meta tag get.metaImport{Prefix:"crawshaw.io/sqlite", VCS:"git", RepoRoot:"https://github.com/crawshaw/sqlite"} at //crawshaw.io/sqlite?go-get=1
go: finding crawshaw.io/sqlite v0.1.3
go get crawshaw.io/sqlite@v0.1.3: crawshaw.io/sqlite@v0.1.3: invalid version: unknown revision v0.1.3
```

main.go:
```
package main

import (
	"crawshaw.io/sqlite/sqlitex"
	"fmt"
	"log"
)

func main() {
	err := Main()
	if err != nil {
		log.Fatal(err)
	}
}

func Main() error {
	dbpool,err:=sqlitex.Open("file:memory:?mode=memory", 0, 10)
	if err != nil {
		return err
	}

	fmt.Printf("got pool %v\n", dbpool)

	return nil
}
```

**Comment by AdamSLevy** [comment]
This is normal behavior for go modules when you update to an untagged commit that is after a tagged version.

**Comment by distributed** [comment]
Is everything about the behavior I see expected to you?

How come that a v0.1.3 seems to exist (I guess it's existence from the version name when updating to master) but I cannot update to it?

**Comment by AdamSLevy** [comment]
> Is everything about the behavior I see expected to you?

Yes. The latest version tag is v0.1.2. The latest commit on master is past that point. When you run `go get crawshaw.io/sqlite@master` you are instructing it to fetch the latest commit on master. Go modules gives this commit a name in your go.mod file and part of that name includes what you might call a "pseudo" version, which is a minor version above the most recently published tagged version.

When you run `go get crawshaw.io/sqlite@v0.1.3` it fails because this tag does not exist.

When you run `go get crawshaw.io/sqlite` it gets the latest tagged commit, which is v0.1.2.

All of this is normal behavior.

Sometime later today I will release a new minor version that includes bug fixes and a few extra features. This will be `v0.2.0` so just look out for that sometime this week.

**Comment by distributed** [comment]
Thank you for the thorough explanation. Now I understand.

I wasn't aware of the minor+1 pseudo commit. TIL :)
